### ISSUE TITLE
Review Trap items from #33

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/SmartHarvestSE#180]
Prior Nexus report

> http://en.uesp.net/wiki/Skyrim:Traps, I am referring to Tension Cable (Editor ID: TrapTriggerHinge, this one is a door technically),
Weight Sensitive Plate (Editor ID: TrapNorPressurePedestal01) and Spellcaster Trap (Editor ID: TrapMagicCasterBase01 and 02).
All are quite common in nordic ruins and can be found in Geirmund's Hall.

**Comment by Lywzc** [comment]
There is already an open issue 35 for this. 33 is for another thing.

**Comment by SteveTownsend** [comment]
thanks, I did not want to lose it but missed the dup
