### ISSUE TITLE
Smart Harvest breaks Fortify Carry Weight

### ISSUE THREAD

**Issue by khokkanen** [SteveTownsend/SmartHarvestSE#194]
I have an item that uses Fortify Carry Weight to boost how much I can carry. On every load game or if Smart Harvest is restarted any other way the mod resets carry weight back to its un-Fortified value. When the item that fortifies carry is removed the carry weight is naturally reduced and this leads to my carry weight sometimes becoming negative.

I can circumvent this by removing the item in question when starting the mod but it gets a bit tedious to do this with every save.

**Comment by SteveTownsend** [comment]
Do you have any of the Carry Weight checkboxes in SHSE turned on? Those are known to be disruptive of more subtle carry-weight adjustments but should be zero impact if disabled.
Is the item in the game or a mod? I can test locally if I know it's FormID, or enough info to track it down and add in console

**Comment by khokkanen** [comment]
- Latest Nexusmods release.
- Carry weight boxes are all off.
- It's a mod item, haven't yet tried with vanilla items. I can try with one later tonight. I'll have to check from wiki what vanillas have the enchantment.

**Comment by SteveTownsend** [comment]
Don't worry, I can probably track one down and try this, if the cause is not obvious from reading the code. If the checkboxes are all off this sounds like a defect for sure, nothing is supposed to get touched in that case. Thanks for the info.

**Comment by khokkanen** [comment]
Agh. Sorry, I did have 'Unencumbered in player home' on. It was the issue, not the mod as a whole. I just remembered that nothing that said 'weight' was on but now that I checked it again there was 'unencumbered'. Strangely the issue rose everywhere, not just home.

**Comment by SteveTownsend** [comment]
OK. I did review the mod code again and it should be water-tight if the flags are not used. Glad it's sorted out.
