### ISSUE TITLE
Use U/K hotkeys to whitelist or blacklist items in world

### ISSUE THREAD

**Issue by zauberparacelsus** [SteveTownsend/SmartHarvestSE#247]
Currently, the U and K hotkeys can be used to add locations or containers to the whitelist and blacklist.  Would it be possible to extend this to individual items that are out in the world, so that you can whitelist or blacklist them without taking them into your inventory?

Reason for this is because some items may do things when picked up.  For example, the CACO mod causes the human flesh item (which I always try to blacklist) to get turned into hominid flesh when taken into your inventory.

**Comment by SteveTownsend** [comment]
I'll take a look, I have a few changes backed up that I'd like to work on this month. I am concerned that the item in the crosshair often won't line up exactly with a single lootable item, or that the lootable item might be hard to intuit quickly. It might be preferable to solve this problem by tailoring a personal blacklist using Collections.

**Comment by SteveTownsend** [comment]
This is fixed for v3.8.0.0
