### ISSUE TITLE
Septims not getting looted when "Handle excess crafting items" is enabled

### ISSUE THREAD

**Issue by dysmasin** [SteveTownsend/SmartHarvestSE#282]
When setting a limit on excess crafting items, septims do not get looted when the target limit is reached.
Disabling this feature fixes this.

Would it be possible to exclude septims from the crafting items?

**Comment by SteveTownsend** [comment]
Yes they should not be affected, I expect some COBJs have dependency on a monetary contribution. I'll try to check for anything else in this line.

**Comment by dysmasin** [comment]
Can confirm. I just created a custom patch with Gold/0x0000000f  removed from all COBJs and it started picking it up again even with "Handle excess crafting items" enabled.

**Comment by SteveTownsend** [comment]
Fix applied for v3.9.3.0
