### ISSUE TITLE
Green Thumb perk is yet again not displayed properly.

### ISSUE THREAD

**Issue by Lywzc** [SteveTownsend/SmartHarvestSE#319]
![ScreenShot0](https://user-images.githubusercontent.com/17480592/140893554-a2d55fef-7ecb-47c9-bb54-1ac19c00d936.png)

**Comment by Lywzc** [comment]
Those Blue Mountain Flowers should be (2). Strangely Butterfly Wing is correct.

**Comment by Lywzc** [comment]
BTW the bug does not appear in 2.8.0.0, although in that version all Mountain Flowers are called "Mountain Flowers
![ScreenShot1](https://user-images.githubusercontent.com/17480592/140906314-354135ce-1b76-491b-b7cd-3ea3fb1d335a.png)
"

**Comment by SteveTownsend** [comment]
I am closing this as ingredient notifications were being routed down the wrong script codepath. Needs rechecking in v3.10.0.0
