### ISSUE TITLE
Investigate Line of Sight restriction to prevent looting in the next room etc.

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/SmartHarvestSE#33]
https://forums.nexusmods.com/index.php?showtopic=8799893/#entry81999418

> I am not so concerned with locked door if you can see the item, the first question is more towards chests that are out of normal cell area (like the chest I reported or chests and items mods may place outside of the normal area for special purposes).

**Comment by SteveTownsend** [comment]
An idea for this:
- add a config switch for 'don't loot behind doors'(edited)
- when scanning local cells, find the nearest DOOR object in range and restrict scan range to that
- need to add logic to prefer 'nearest' loot anyways, so include DOOR as loot, sort by distance  and cut off the lootables at first DOOR
Most often you are either far enough from any door for this not to matter, or walking towards it to unlock/change location and so will pick up 'nearby stuff' en route
Issues w this:
- if you are standing on a trapdoor, it messes up looting of current room (e.g. the Malrus Codex case). Mitigation: if you use this setting, you know enough to sweep the space.

**Comment by Lywzc** [comment]
But in the game some other strange stuff also use DOOR, like the chest trap I mentioned earlier.

**Comment by SteveTownsend** [comment]
> But in the game some other strange stuff also use DOOR, like the chest trap I mentioned earlier.

I have not done any data analysis yet, I imagine there is a way to restrict this to true doors/cells/trapdoors. I'd also like to restrict to the same floor so I don't loot a cellar or upper floor while on the main floor, for example.

**Comment by jtolmer** [comment]
As an FYI, I was playing yesterday and Smart Harvest looted the Ancient Shrouded Armor through the hidden door that blocks access to it. I'm far enough into the Dark Brotherhood quest line to have unlocked the ability to open said hidden door. So, a possible place to test any fix you're making.

**Comment by SteveTownsend** [comment]
Working through 1.5 issues, this is next

**Comment by SteveTownsend** [comment]
_LootSense_ aka _Fortune Hunter's Instinct_ in v2.7.0.0 is the last planned work here
