### ISSUE TITLE
Player home issue.

### ISSUE THREAD

**Issue by Lywzc** [SteveTownsend/SmartHarvestSE#332]
In the current version I noticed you do not need to whitelist your home to loot it which is not ideal. Player-owned items and chest used to not override your home. This option used to only work outside of player home.

Second, glowing for quest items are active in player homes which makes your chests glowing which is undesired.

**Comment by Lywzc** [comment]
These two issues do not exist on the last version 3.10.0.0 so I think perhaps the new LootAllowedItemsInPlayerHouse caused issue.

**Comment by SteveTownsend** [comment]
yes this was a pretty small code change but high impact. I'll look at the
issues you've noticed, thanks

**Comment by SteveTownsend** [comment]
I have a small fix that should reinstate prior behaviour unless _LootAllowedItemsInPlayerHouse_ is true. If player sets this, I think the other behaviours are an OK trade off - this avoids a bunch of complex switching logic if this flag is set. Fixed for v3.10.2.0
