### ISSUE TITLE
Arrows looted mid-air when player is experiencing Slow Time

### ISSUE THREAD

**Issue by Lywzc** [SteveTownsend/SmartHarvestSE#333]
![ScreenShot6](https://user-images.githubusercontent.com/17480592/143729035-cfb5ade5-bd18-463f-892b-8a4886774333.png)

**Comment by SteveTownsend** [comment]
Two approaches implemented for v3.10.4.0
- reduce the movement-detected threshold for in-flight arrows by a factor of 5 (for player and NPC arrows)
- do not loot moving arrows at all if player is subject to MGEFs with Archetype SlowTime or Archetype ValueModifier on value BowSpeedBonus

**Comment by Lywzc** [comment]
Well, one is sufficient and I think the first one is better since the second will make you 16 seconds unable to loot moving arrows if you use Slow Time.

**Comment by SteveTownsend** [comment]
The final fix is to restore the original handling unless player is experiencing Slow Time, then reduce the arrow-moving distance to 20% of normal. Let me know if you are willing to test again before I push this out. It also scales properly now with loot scan interval.

**Comment by Lywzc** [comment]
I can test if you have the file.

**Comment by SteveTownsend** [comment]
Thanks - updated DLL is at https://drive.google.com/file/d/19lL_RIbozoP8lcFZe14IFfRnrLT_9AFK/view?usp=sharing. It works OK for vanilla ammo looting but I have not tried any of the Slow Time cases.

**Comment by Lywzc** [comment]
It works well for Slow Time and Steady Hands, others untested but should be fine too.

**Comment by SteveTownsend** [comment]
Thanks for testing - I'll release this once Whitelist is sorted out. The nice thing about the fix is that provided a MGEF follows one of the rules, modded MGEFs will all 'just work'.
