### ISSUE TITLE
Can not whitelist Lakeview Manor

### ISSUE THREAD

**Issue by Lywzc** [SteveTownsend/SmartHarvestSE#334]
I am building it and I can not whitelist it. It keep saying remove from whitelist.

**Comment by Lywzc** [comment]
I can only resolve it by reloading an much earlier save.

**Comment by Lywzc** [comment]
![ScreenShot9](https://user-images.githubusercontent.com/17480592/145408716-452ebb6a-9203-49ef-aa11-70a1ae009550.png)
This seems to happen if you press U too early into the house.

**Comment by SteveTownsend** [comment]
what am I looking at in this screenshot?

**Comment by Lywzc** [comment]
When I first enter and press U it shows Markarth added, then I pressed again then VH added but no looting happen, in mod settings Markarth is there but not VH. Unchecked Markarth then Markarth Removed, U again and VH removed, but after that U and you still get VH removed.

**Comment by SteveTownsend** [comment]
OK, it should not whitelist Markarth after you have entered the player house. I'll have a look this weekend if time permits.

**Comment by SteveTownsend** [comment]
Fix applied for v3.10.4.0 - always refresh _LocationTracker_ so we act on current data when using blacklist/whitelist hotkey. [If the data lags and gives us a stale result, there's not much more that can be done.]
