### ISSUE TITLE
The clones of Halldir should not be lootable.

### ISSUE THREAD

**Issue by Lywzc** [SteveTownsend/SmartHarvestSE#335]
Reason same as Companion Ghosts. However the main Halldir is lootable.
The former has BaseID of 642C1, 642C2, 642C3 and RefID of 642C4, 642C5, 642C6 while the latter has BaseID of 64B1C and RefID of 642C0.

**Comment by SteveTownsend** [comment]
I've added these to the same list as Companion Ghosts for v3.10.4.0.
