### ISSUE TITLE
Sigdis Gauldurson's clones should not be auto looted.

### ISSUE THREAD

**Issue by Lywzc** [SteveTownsend/SmartHarvestSE#337]
Reason same as before. BaseID A6848, no RefID since they are spawned using script.

**Comment by Lywzc** [comment]
Also three Gaulursons and Sigdis Gauldurson's clones in Reachwater Rock. BaseID A6842, ECF13, 1BB28, AB6FF. RefID ECECD, None, ECECE and ECECC.

**Comment by SteveTownsend** [comment]
Seems like there is a whole raft of NPCs tagged as ActorTypeGhost that should be skipped. Will try that.

**Comment by SteveTownsend** [comment]
Agreed, I will special case the ones that are not covered by _ActorTypeGhost_ for v4.0.0.8

**Comment by SteveTownsend** [comment]
Ghosts keyword on 1BB28 handles that one
