### ISSUE TITLE
Wisp Cores should not be categorized as critter

### ISSUE THREAD

**Issue by Lywzc** [SteveTownsend/SmartHarvestSE#342]

**Comment by SteveTownsend** [comment]
This was previously fixed under https://github.com/SteveTownsend/SmartHarvestSE/issues/164. If you have a different item failing, please add details.

**Comment by Lywzc** [comment]
Nothing changed. It simply does not work.

**Comment by Lywzc** [comment]
OK I found out the problem is treating them as critters. Since critters include fish and butterflies I usually disable them to avoid mass hunting. If it can be changed, flora, ore vein or container should be better.

**Comment by SteveTownsend** [comment]
ah OK, I'll take a look - thanks for continued reports

**Comment by Lywzc** [comment]
Critters are quite different from any other kinds in that they are not respawned but spawned. So basically they are not bound by respawning time and large quantity can be quickly gathered. For this reason I avoid enabling them but wisp cores certainly do not belong to their kind.

**Comment by SteveTownsend** [comment]
I don't think any of the suggested alternate categories make any more sense than _critter_. I'm not going to alter this item's handling. You should be able to whitelist them manually, or use a permanent whitelist collection like below.
```
{
  "$comment": "Definitions are allowed for up to 128 rulesets for Collections",
  "$schema": "./SHSE.SchemaCollections.json",
  "groupPolicy": {
    "action": "take",
    "notify": false,
    "repeat": true
  },
  "useMCM": false,
  "collections": [
    {
      "name": "Whitelist 1",
      "description": "Whitelist 1",
      "rootFilter": {
        "operator": "AND",
        "condition": {
          "forms": [
            {
              "$comment": "Wisp Core",
              "plugin": "Skyrim.esm",
              "form": [ "0010AB2A" ]
            }
          ]
        }
      }
    }
  ]
}
