### ISSUE TITLE
AE - automining oreveins not working

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/SmartHarvestSE#343]
report from Nexus user Oblitus - provide Debug DLL for diagnostics to be gathered.

**Comment by zarantha** [comment]
There were no updates to the CK for AE, so the actual psc files are the same for both AE and SE.
I've decompiled the minorescript.pex from AE just in case it changed.

[mineorscript.zip](https://github.com/SteveTownsend/SmartHarvestSE/files/7798193/mineorscript.zip)

**Comment by SteveTownsend** [comment]
It looks the same. I am building a Logging DLL that should be more stable than the full Debug one, for v4.0.0.8

**Comment by SteveTownsend** [comment]
Add some script logging for this case in v4.0.0.10

**Comment by SteveTownsend** [comment]
Script logging enabled for Logging and Debug builds - release in v4.1.0.0

**Comment by SteveTownsend** [comment]
Test evidence for _oreVein_ script logging without Debug DLL
```
2022-01-08 13:47:27.429     info   9404 Script logging active
```
```
```
