### ISSUE TITLE
Wolf Spirits still looted.

### ISSUE THREAD

**Issue by Lywzc** [SteveTownsend/SmartHarvestSE#344]
Tested with my own wolf spirit since I decide to cure myself.  May be the same issue as Companion Ghosts.

**Comment by SteveTownsend** [comment]
Seems like there is a whole raft of NPCs tagged as ActorTypeGhost that should be skipped. Will try that.

**Comment by SteveTownsend** [comment]
the fix to not loot NPCs with activation blocking will be in v4.0.0.8
