### ISSUE TITLE
Debug DLL for AE causes CTD

### ISSUE THREAD

**Issue by zarantha** [SteveTownsend/SmartHarvestSE#345]
Game crashed with the debug dll. Normal dll for 4.0.0.5 loads without issue.

SmartHarvestSE.log
https://pastebin.com/G3MUHwWE

crash-2021-12-24-19-19-32.log
https://pastebin.com/E0kHFB8m

**Comment by SteveTownsend** [comment]
I'll ship a logging version of Release instead - v4.0.0.8
