### ISSUE TITLE
Savos Aren's body should not be lootable.

### ISSUE THREAD

**Issue by Lywzc** [SteveTownsend/SmartHarvestSE#347]
In Containment, after he is dead he is not interactable, so his body should not be lootable.
Alias_MG05SavosArenAlias.GetReference().BlockActivation(true) in QF_MG05_0001F255

**Comment by SteveTownsend** [comment]
I am going to try to skip any NPC with activation blocked - that is not checked right now

**Comment by SteveTownsend** [comment]
the fix to not loot NPCs with activation blocking will be in v4.0.0.8
