### ISSUE TITLE
Autolooting Morokei seems to make Staff of Magnus unequippable.

### ISSUE THREAD

**Issue by Lywzc** [SteveTownsend/SmartHarvestSE#348]
Tested several times. If you disable autolooting before killing him, no matter how you loot it (Take all or take one by one) Staff will always be equippable. Enable autolooting and Staff will always be unequippable.
Note that Staff of Magnus itself is not looted in autolooting. Simply autolooting Morokei will cause the problem.

**Comment by SteveTownsend** [comment]
the usage of the Staff in scripts is nightmarishly complex. I propose to blacklist Morokei as a bespoke Quest Target rather than try to work this out properly. Fix is in v4.0.0.8
