### ISSUE TITLE
The spectral assassin should not be looted.

### ISSUE THREAD

**Issue by Lywzc** [SteveTownsend/SmartHarvestSE#351]
He is a summoned actor and although he will leave ghostly remains, they are not lootable.

**Comment by SteveTownsend** [comment]
Seems like there is a whole raft of NPCs tagged as _ActorTypeGhost_ that should be skipped. Will try that.

**Comment by Lywzc** [comment]
Well not really. For example Yngvild Ghosts are lootable.

**Comment by Lywzc** [comment]
After some investigation, it seems that there is a variable called bFade in defaultGhostScript. If this variable is true for a ghost then it will not be lootable. 
	IF(bFade)
		SELF.blockActivation(TRUE)
		disable(1)
The default value is false. So it is still a blockActivation issue.

**Comment by Lywzc** [comment]
However, the case with spectral assassin is more special. He is summonable but at the same time can leave a corpse. As we all know we can not loot summons, so his corpse is also not lootable.

**Comment by SteveTownsend** [comment]
This NPC_ looks like every other using _defaultGhostScript_, I am not adding special handling for this

The catch-all fix to not loot NPCs with activation blocking will be in v4.0.0.8
