### ISSUE TITLE
Highlight looted container setting not saved

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/SmartHarvestSE#36]
https://forums.nexusmods.com/index.php?showtopic=8799893/#entry81986608

> The Highlight looted container settings does not get saved for whatever reason, if I reload the game then the setting is back to Glow Briefly.

**Comment by SteveTownsend** [comment]
This could be due to defaults being erroneously restamped on game reload

**Comment by SteveTownsend** [comment]
I could not reproduce this. Park, try again before v1.1.0.0 upload

**Comment by Lywzc** [comment]
I did not get this to work once. My process:
Load the game, set Highlight looted container to No Action, save the INI in the first tab, save the game, reload the game I just saved, boom, the setting is back to Glow Briefly.

**Comment by SteveTownsend** [comment]
> I did not get this to work once. My process:
> Load the game, set Highlight looted container to No Action, save the INI in the first tab, save the game, reload the game I just saved, boom, the setting is back to Glow Briefly.

the mod is hidden right now, the MCM and settings management needs a major cleanup. Planning to update later on June 13

**Comment by SteveTownsend** [comment]
v1.1.0.0 should fix this, though I could not repro
