### ISSUE TITLE
Looting of NPCs happens at the wrong time

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/SmartHarvestSE#37]
https://forums.nexusmods.com/index.php?showtopic=8799893/#entry81986608

> When Farkas transforms into werewolf form in Proving Honor, his Skyforge Steel Greatsword will get looted which is undesired. Aela in The Silver Hand should be the same.

**Comment by Lywzc** [comment]
Also when the conjured atronachs disappear, we will loot fire salts etc. which is bad. Perhaps add a delay before looting?

**Comment by SteveTownsend** [comment]
> Also when the conjured atronachs disappear, we will loot fire salts etc. which is bad. Perhaps add a delay before looting?

Is this report for self-conjured, summoned by an enemy. or both? The logic is different depending on who summoned it.

We cannot wait any longer to loot these, or the game will crash. Trust me on that.

**Comment by Lywzc** [comment]
Self-conjured, I literally added this spell to my character to test this case.

Then another way may have to be found to prevent this problem.

**Comment by Lywzc** [comment]
And it is the same for enemy conjured ones.

**Comment by SteveTownsend** [comment]
Thanks for all the info. I"ll get to this during the week, but taking a short breather after the crunch of releasing. I am also confused because I thought bound fire atronachs were not supposed to drop fire salts per https://en.uesp.net/wiki/Skyrim:Daedra#Flame_Atronach. 

It's possible I could re-introduce a delay before looting these in the light of other recent changes to that area, though I'm not sure what that would achieve, unless the loot appears and then the remains of the summon are cleaned up before manual looting is humanly possible? 

The logic is not supposed to loot summons so maybe that's just not working right - that would likely be the easiest fix.

**Comment by Lywzc** [comment]
That is because in normal play only unbound varieties leave corpses, bound varieties simply vanish making them impossible to loot normally.

**Comment by SteveTownsend** [comment]
Port of AHSE logic for NPC/ActorCharacter looks incorrect, esp. for summons which only applies if ActorCharacter is an NPC

**Comment by SteveTownsend** [comment]
Test evidence for self-conjured Flame Atronach being unlootable after the fix:
```
J:\GitHub\SmartHarvestSE\src\Looting\tasks.cpp(1056): [VERBOSE] {44560} (2020-07-02 05:13:51 PM) Process REFR 0xff002310 with base object Flame Atronach/0x000204c0
J:\GitHub\SmartHarvestSE\src\Looting\objects.cpp(112): [DEBUG] {44560} (2020-07-02 05:13:51 PM) Actor is follower = false
J:\GitHub\SmartHarvestSE\src\Looting\objects.cpp(128): [DEBUG] {44560} (2020-07-02 05:13:51 PM) Actor summoned = true
J:\GitHub\SmartHarvestSE\src\Looting\tasks.cpp(1080): [VERBOSE] {44560} (2020-07-02 05:13:51 PM) Block ineligible Actor 0xff002310, base = Flame Atronach/0x000204c0
```
This fix also affects Essential Actor handling so it could fix Farkas/Aela, but I have not proven that. Anyway this will be in v1.6 -  closing for now.
