### ISSUE TITLE
Ghost auto-loot prevention too restrictive

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/SmartHarvestSE#374]
Nexus report

> I went through Rannveig's Fast just now and the piles left over from the subjugated ghosts didn't get looted. Has anyone else had something similar, or is it just a random act of non-looting? Normally everything should be looted, especially the remains of those ghosts.
> 
> The piles were lootable, so they should've been auto looted as you say, but they weren't. Unfortunately, the piles had already been cleaned up when I got back to them now. What they give is ectoplasm and something I don't remember at the moment.
> 
> Edit: I just now killed the Ancient Traveller, and he left behind a "Ghostly Remains", an activator with ref ff0010b4, base 00101048. Didn't loot by itself.

**Comment by Lywzc** [comment]
Although ghosts are not auto looted, it seems that those ash piles or remains attached to them are also not which is the problem.
			SELF.AttachAshPile(pDefaultAshPileGhost)
			
			IF(bdefaultLoot)
				SELF.RemoveAllItems()
				SELF.addItem(pdefaultGhostLeveledList)
			ENDIF
And, IsGhost has nothing to do with the actor type.
