### ISSUE TITLE
failing to steal in some Whiterun shops

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/SmartHarvestSE#402]
Nexus report from YilanSG
https://forums.nexusmods.com/index.php?/topic/8799893-smart-harvest-se/?p=118764538

>  I'm getting what I think is a bug when stealing in certain places, like the drunken huntsman and the bannered mare. The mod just refuses to steal anything even when I am completely hidden. I tried whitelisting the place but that didn't appear to work, I've also tried messing around with the settings to no avail. This has only happened in those two places so far.
> 
> What is really weird is that when I closed the game and opened it again after a few hours, I could steal inside the bannered mare again, but not the drunken huntsman...

**Comment by austindavidson1224** [comment]
Smart harvest was working fine until I accidently blacklisted Whiterun and now nothing will loot even though I removed from blacklist any thoughts.

**Comment by SteveTownsend** [comment]
Check this out, changes in theft handling might have resolved

**Comment by SteveTownsend** [comment]
Theft handling and blacklist changes under #417 mean this needs a revisit by user. Closing for now vs v5.6.0
