### ISSUE TITLE
CC Fishing fishes inconsistent

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/SmartHarvestSE#406]
Nexus report from Mordre:

> I'm wondering about the fish added by the Fishing CC. I've had a lot of experiences of salmon, arctic char and the other wozznames not being harvested, and I wonder wether this is because of something I did, or if it is SmartHarvest not recognizing the CC's activators?
> Though some works, so that makes me confuzzled. Such as carps.

**Comment by Ghostwalker71** [comment]
I have not had any issues with the fish from cc fishing being harvested, they continue to harvest even when I am over stocked, But I did find that smart harvest will cause the fishing minigame to hang. It appears that smart harvest will harvest the fish when it is displayed to the player then the fishing minigame tries to move the fish to inventory but it has already been moved and the screen remains in display mode, the only way out once it happens is to exit the game or reload an earlier save. Pausing Smart Harvest before fishing is a workaround.  I don't know how hard it would be to hook into the fishing minigame but it would be nice if Smart Harvest could auto pause while fishing is active.

**Comment by SteveTownsend** [comment]
ugh. I'll have a look at this once I get back to development work on the mod.

**Comment by SteveTownsend** [comment]
Probably just need to disable looting of _critterFish_ ACTI while the state of _ccBGSSSE001_FishingSystemScript_ is not IDLE. Reproduce first and then try that out.

**Comment by SteveTownsend** [comment]
The Fishing Dialogue QUST seems to have a property that can be checked to avoid critter harvesting messing this up

**Comment by SteveTownsend** [comment]
Testing in Riften.
Detection of mod
_2024-02-06 12:34:52.110     info  31340 CC Fishing present = TRUE_
Disabling critter looting when dialogue QUST active
2024-02-06 12:35:17.274     info  31340 CanHarvest: ccFishingDialogue.dialogueDetectEnabled=1
2024-02-06 12:35:17.391     info 234800 OnHarvestCritter: target [critterFish < (FF000FFD)>], base [Ingredient < (1632608F)>], item type: 3, do not notify: False
2024-02-06 12:35:17.424     info 159708 CanHarvestCritter: ccFishingDialogue.dialogueDetectEnabled=1_
Legit harvesting of fish while Fishing Supplies inactive
_2024-02-06 12:36:50.683    trace  59276 SmartHarvest Cyrodilic Spadetail/0x00106d2b for Critter REFR 0xff00100b, collectible=false, type ingredient, notify true, pending 1
2024-02-06 12:36:50.767     info 192944 OnHarvestCritter: target [critterFish < (FF00100B)>], base [Ingredient < (00106E19)>], item type: 3, do not notify: False
2024-02-06 12:36:50.800     info 240520 CanHarvestCritter: ccFishingDialogue.dialogueDetectEnabled=0
2024-02-06 12:36:50.834     info  31340 OnHarvestCritter:Activated:[critterFish < (FF00100B)>]_
