### ISSUE TITLE
Collection dropdown missing SUT

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/SmartHarvestSE#439]
Nexus report from [HadToRegister](https://www.nexusmods.com/users/923152)

> Using this with Skyrim AE 1.6.1170, it's working fine, except it doesn't want to see Skyrim Unique Treasures in the Collection Drop-down
> I know this used to work, because I would always use the drop down to pick between LOD and SUT.
> 
> Collection JSON files are in the PLUGINS Directory

**Comment by SteveTownsend** [comment]
This worked OK for me. Requested user to add a screenshot and Collections JSONs here

**Comment by HadToRegister** [comment]
Hope I did this correctly

[SHSE.Collections.BlackList.json](https://github.com/SteveTownsend/SmartHarvestSE/files/14104233/SHSE.Collections.BlackList.json)
[SHSE.Collections.ManualLoot.json](https://github.com/SteveTownsend/SmartHarvestSE/files/14104234/SHSE.Collections.ManualLoot.json)
[SHSE.SchemaCollections.json](https://github.com/SteveTownsend/SmartHarvestSE/files/14104238/SHSE.SchemaCollections.json)
[SHSE.SchemaFilters.json](https://github.com/SteveTownsend/SmartHarvestSE/files/14104239/SHSE.SchemaFilters.json)
![SHSE Screenshot](https://github.com/SteveTownsend/SmartHarvestSE/assets/52507578/d3ad0616-40a5-49ec-8a98-f724b4309fcc)

**Comment by SteveTownsend** [comment]
Where is the JSON with the SUT collection in it? That's in *Examples* by
default and has to be moved alongside the mandatory files.

**Comment by SteveTownsend** [comment]
User fixed this by himself
