### ISSUE TITLE
situational Store/Location whitelisting

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/SmartHarvestSE#44]
Report from Vyxenne at Nexus https://forums.nexusmods.com/index.php?showtopic=8799893/#entry82022088

> I can't find a way (in the MCM) to override the location rules when the occasion demands- for example, when a certain shop in Windhelm become ownerless, I need to tell SH to override the Windhelm exemption and any Merchant Store exemptions and auto-loot it while still leaving the Windhelm and other shop exemptions in place.

**Comment by Lywzc** [comment]
Also I will want to loot my own house the first time I entered it to rid the house of initial garbage.
And it should bring up a confirmation window in case you triggered looting in these places unintentionally. So if you are going to whitelist a potentially questionable place it will ask you to confirm your decision.

**Comment by SteveTownsend** [comment]
confirmation is covered under #48 - fix here will be to allow hotkey whitelist add/remove while in worldspace

**Comment by SteveTownsend** [comment]
Cleaned up whitelist/blacklist and modified hotkeys logic while in worldspace to add current location/cell to WhiteList (or BlackList)

**Comment by SteveTownsend** [comment]
fixed in v1.3.0.0
