### ISSUE TITLE
Nothing glowing.

### ISSUE THREAD

**Issue by Raveness69** [SteveTownsend/SmartHarvestSE#456]
Everything else is working great, but no glow at all. Below is the trace log from the logging mod.

[SmartHarvestSE.log](https://github.com/SteveTownsend/SmartHarvestSE/files/14399397/SmartHarvestSE.log)

**Comment by SteveTownsend** [comment]
Seems like not everybody is having this problem. Could be timing of TaskInterface is not the same as script invocation?
Check why full diagnostics are not coming out from Logging DLL.
Try to make the logic more resilient - don't discard the queued glow requests, handle dupes that arrive if stuff is already queued.

**Comment by SteveTownsend** [comment]
Here's output after changing the log-level setup to just alter my log. Maybe this will fix the missing _debug_ logs?
![image](https://github.com/SteveTownsend/SmartHarvestSE/assets/14825099/b1aab17d-67cc-4127-99ce-89045dce884f)

**Comment by SteveTownsend** [comment]
Improved diagnostics in this area for v5.6.0. Not clear to me what is going on.

**Comment by SteveTownsend** [comment]
Could be related to script interactions analogous to #417.

**Comment by SteveTownsend** [comment]
Leaving this open for next milestone - may be able to close, depending on feedback on v5.6.0

**Comment by PoptartJuniper** [comment]
I'm linking my logs from my drive, they are way too large for github apparently. The last version I actually played with was 5.1 and the glow works. Switching back to 5.1 activates the glow again.

https://drive.google.com/drive/folders/1aDYS9sBKVhkNeSi8f3TFWtbjdP8VoIfN?usp=sharing

**Comment by SteveTownsend** [comment]
Thanks for the log, I should be able to hotfix this later on today by relaxing the check on whether it's OK to glow items.

```
2024-03-24 12:30:00.402    trace  52596 IsActivateControlsEnabled false
2024-03-24 12:30:00.402  warning  52596 Delay 31 queued Glow requests, scan status NoActivateControls
```

**Comment by SteveTownsend** [comment]
Split the check for OK-to-scan into two - OK-to-activate (fine grain) and OK-to-scan, and applied logic changes as appropriate wherever the old brute force check was used
