### ISSUE TITLE
Oblivion Interaction Icons missed cases

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/SmartHarvestSE#461]
Nexus report from [Bomber22](https://www.nexusmods.com/users/3121493) - related to mixed case in the OII mod. Fix tested by reporting user:

> The comma-separated strings are regular expressions so this should work for all, if your hypothesis is correct.
> `Catch.*,<[Ff]font face="Iconographia">[SV]</[Ff]ont>.*`

**Comment by stardnce** [comment]
Oddly this didn't work for me, but your original solution (`Catch.*,<font face="Iconographia">[SV]</Font>.*`) on Nexus comments worked fine. Mod not catching butterflies while Oblivion Icons synthesis patch was active was my specific issue.

**Comment by SteveTownsend** [comment]
The string from above is wrong has too many F characters in the opening tag

_Catch.*,<[Ff]font face="Iconographia">[SV]</[Ff]ont>.*_

It should be like this, and this is what got released.

_Catch.*,<[Ff]ont face="Iconographia">[SV]</[Ff]ont>.*_
