### ISSUE TITLE
Loose lootables not being harvested

### ISSUE THREAD

**Issue by PoptartJuniper** [SteveTownsend/SmartHarvestSE#474]
Only containers seem to be looted, for both sneaking stealing and non sneaking regular looting.

Link to log: https://drive.google.com/drive/folders/1aDYS9sBKVhkNeSi8f3TFWtbjdP8VoIfN?usp=sharing

**Comment by SteveTownsend** [comment]
Please try the prerelease update file v5.6.2, logging version only for now

**Comment by PoptartJuniper** [comment]
The game freezes when loading my save.

Here's the log generated https://drive.google.com/file/d/1I9mameFq6TBWHwWOsnRL2W-p26hYBZID/view?usp=drive_link

**Comment by SteveTownsend** [comment]
I have no idea what caused that. I consider it unlikely to be the changes I just made, frankly.
Are you using Quick Saves?
You could try cleaning up the SHSE script instances with Resaver but since I don't understand what happened here,I don;t have great confidence that will fix it.

**Comment by PoptartJuniper** [comment]
I don't use quick saves. Resaver reports nothing to be cleaned in my save. I made a new save when you said the mod needed a new save to update. I even loaded an earlier save just to make sure I didn't load an auto save on accident the first time.

**Comment by SteveTownsend** [comment]
The Smart Harvest main quest is not being detected. That's unrelated to looting logic that I just changed.

**Comment by SteveTownsend** [comment]
Let me know if you have a save that will load which you can test this on. I'm pushing the release out anyway as it worked for me (again) and completely removes the harvest constraint that you were hitting before.

**Comment by SteveTownsend** [comment]
There is no visible malfunction of the mod in this log.
We need to narrow down to one failing item to make this go quicker.
Pick the item.
Set your settings as desired.
Get log of failure.
Send me the log with the settings.
Preferably, get a blacklist hotkey long press screenshot of your item as described in the first sticky post.

**Comment by PoptartJuniper** [comment]
First I chose some snowberries in Winterhold, they would not loot. I took screenshots but I didn't have the logger running. So I saved, activated the logger and reloaded, then the snowberries were looted upon reload.

Second was in the College of Winterhold. Nothing was looting in there, not even containers. Chose a food item, said I was detected (not sneaking or stealing) by an npc but in winterhold. Reloaded the auto save when I entered, regular lootables looted as expected but nothing would steal even when hidden.

New log and screenshots. https://drive.google.com/drive/folders/1aDYS9sBKVhkNeSi8f3TFWtbjdP8VoIfN?usp=drive_link

**Comment by SteveTownsend** [comment]
Smoking gun from [jmathgun](https://www.nexusmods.com/skyrimspecialedition/users/107272793) here. I see the same behaviour.

> i just tested it on a vanilla instance with only the dependencies installed. it picked up things until I opened any menu, then stopped. this includes the main menu and the magic menu not just the inventory.

**Comment by SteveTownsend** [comment]
Reported fixed
