### ISSUE TITLE
Harrada Root CTDs in the oblivion gate

### ISSUE THREAD

**Issue by cde2496** [SteveTownsend/SmartHarvestSE#483]
I have CDT in the oblivion gate seems linked to 'Harrada Root'
[Crash_2024_5_15_18-41-11.txt](https://github.com/SteveTownsend/SmartHarvestSE/files/15320339/Crash_2024_5_15_18-41-11.txt)
[Crash_2024_5_15_18-44-44.txt](https://github.com/SteveTownsend/SmartHarvestSE/files/15320341/Crash_2024_5_15_18-44-44.txt)
[Crash_2024_5_15_18-49-45.txt](https://github.com/SteveTownsend/SmartHarvestSE/files/15320343/Crash_2024_5_15_18-49-45.txt)

**Comment by cde2496** [comment]
FYI, I am using Nolvus v5 but heavily modified with additional mods.

**Comment by SteveTownsend** [comment]
I reproduced this after entering the Gate. I only tested CC flora in the plant test call, obvs that was insufficient
```
PROBABLE CALL STACK:
	[ 0] 0x7FF96239FD0F SmartHarvestSE.dll+016FD0F	mov eax, [r8+0x14] |  I:\GitHub\SmartHarvestSE\src\VM\papyrus.cpp:310 ?SetLootableForProducer@papyrus@@YAXPEAUStaticFunctionTag@RE@@PEAVTESForm@3@1@Z
	[ 1] 0x7FF9623B36BA SmartHarvestSE.dll+01836BA	mov rcx, [rsp+0x70] |  I:\GitHub\SmartHarvestSE\build\_deps\commonlibsse-src\include\RE\N\NativeFunction.h:99 ?MarshallAndDispatch@?$NativeFunction@$0A@$$A6AXPEAUStaticFunctionTag@RE@@PEAVTESForm@2@1@ZXPEAU12@PEAV32@PEAV32@@BSScript@RE@@UEBA_NAEAVVariable@23@AEAVVirtualMachine@Internal@23@I0AEBVStackFrame@23@@Z
	[ 2] 0x7FF6AF5EDE05       SkyrimSE.exe+143DE05 -> 104651+0x205	test al, al
	[ 3] 0x7FF962448968 SmartHarvestSE.dll+0218968	mov rbx, [rsp+0x68] |  I:\GitHub\SmartHarvestSE\build\_deps\commonlibsse-src\src\RE\N\NativeFunctionBase.cpp:112 ?Call@NativeFunctionBase@NF_util@BSScript@RE@@UEAA?AW4CallResult@IFunction@34@AEBV?$BSTSmartPointer@VStack@BSScript@RE@@UBSTSmartPointerIntrusiveRefCount@3@@4@PEAVErrorLogger@34@PEAVVirtualMachine@Internal@34@_N@Z

```

**Comment by SteveTownsend** [comment]
Complicated because the harvestable can be either LVLI (CACO patch) or INGR (unpatched). Using base form might work?

**Comment by SteveTownsend** [comment]
Current fix prevents the crash but more work is needed on scripted ACTI that can have diff concrete FormType for Lootable
