### ISSUE TITLE
Stray INI file getting created

### ISSUE THREAD

**Issue by jtolmer** [SteveTownsend/SmartHarvestSE#488]
It seems that this mod is causing a stray INI file to get created when it auto picks up items without notifications. I reproduced with a minimal mod set running Skyrim 1.6.1170.0:
- SKSE
- Address Library for SKSE
- SkyUI
- Smart Harvest

To reproduce:
- Load a save game
- Wait for Smart Harvest start-up notifications to finish
- Shoot an arrow into the ground
- Wait for arrow to be auto picked up
- Exit game
- Notice new, stray INI file in MO2 overwrite directory

The INI file will be named after whatever esp is loaded last. In this minimal repro case, SmartHarvestSE.ini. The contents of the file are
```
[Interface]
bShowHUDMessages=1
```
I tried searching to see if this was already reported / a known issue, but didn't find any other reports. My apologies if this is a duplicate report.

**Comment by SteveTownsend** [comment]
I think this is covered by
https://github.com/SteveTownsend/SmartHarvestSE/issues/481

**Comment by SteveTownsend** [comment]
Should be fixed once #481 fix is released

**Comment by jtolmer** [comment]
Thank you for your work on Smart Harvest. It continues to be appreciated.
