### ISSUE TITLE
CTD reports in v5.9.0

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/SmartHarvestSE#499]
Nexus user [DeadSoulja](https://www.nexusmods.com/skyrimspecialedition/users/4871360)

> I spawned to Riverwood from the main menu, and made my way to Riverside Lodge.
> 
> This crash happened at [Riverside Lodge ](https://www.nexusmods.com/skyrimspecialedition/mods/9567)+ [Follower Edition](https://www.nexusmods.com/skyrimspecialedition/mods/48179).

```
PROBABLE CALL STACK:
    [ 0] 0x7FFF725AC6C0 SmartHarvestSE.dll+008C6C0    movzx ebx, byte ptr [rbx+0x1A] |  I:\GitHub\SmartHarvestSE\src\Looting\ReferenceFilter.cpp:285 ?RecordReference@ReferenceFilter@shse@@AEAAXPEAVTESObjectREFR@RE@@@Z
    [ 1] 0x7FFF725ACB0C SmartHarvestSE.dll+008CB0C    mov rbx, [rbx] |  I:\GitHub\SmartHarvestSE\src\Looting\ReferenceFilter.cpp:402 ?RecordCellReferences@ReferenceFilter@shse@@AEAAXPEAVTESObjectCELL@RE@@_N@Z
    [ 2] 0x7FFF725ACBC3 SmartHarvestSE.dll+008CBC3    test dil, dil |  I:\GitHub\SmartHarvestSE\src\Looting\ReferenceFilter.cpp:425 ?FilterNearbyReferences@ReferenceFilter@shse@@AEAAXXZ
    [ 3] 0x7FFF725AFF6A SmartHarvestSE.dll+008FF6A    nop |  I:\GitHub\SmartHarvestSE\src\Looting\ScanGovernor.cpp:575 ?LootAllEligible@ScanGovernor@shse@@AEAAXXZ
    [ 4] 0x7FFF725B042A SmartHarvestSE.dll+009042A    call 0x00007FFF725B5170 |  I:\GitHub\SmartHarvestSE\src\Looting\ScanGovernor.cpp:659 ?DoPeriodicSearch@ScanGovernor@shse@@QEAAXW4ReferenceScanType@2@@Z
    [ 5] 0x7FFF7260065E SmartHarvestSE.dll+00E065E    jmp 0x00007FFF72600370 |  I:\GitHub\SmartHarvestSE\src\PluginFacade.cpp:250 ?ScanThread@PluginFacade@shse@@CAXXZ
    [ 6] 0x7FFF725FFD59 SmartHarvestSE.dll+00DFD59    int3 |  I:\GitHub\SmartHarvestSE\src\PluginFacade.cpp:126 ?Init@PluginFacade@shse@@QEAA_NXZ
    [ 7] 0x7FFF72600FD9 SmartHarvestSE.dll+00E0FD9    int3 |  C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include\type_traits:1729 ?OnSettingsPushed@PluginFacade@shse@@QEAAXXZ
    [ 8] 0x7FFF72600FB6 SmartHarvestSE.dll+00E0FB6    int3 |  C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include\thread:60 ?OnSettingsPushed@PluginFacade@shse@@QEAAXXZ
    [ 9] 0x7FF8066C1BB2       ucrtbase.dll+0021BB2
    [10] 0x7FF807A57344       KERNEL32.DLL+0017344
    [11] 0x7FF808FFCC91          ntdll.dll+004CC91
```

**Comment by SteveTownsend** [comment]
From Nexus user [xLenax](https://www.nexusmods.com/users/5628401)

> CTD with 5.9.0. When I updated the mod I was inside Ysgramor's Tomb. Clean install blah blah blah, while indoors everything seemed fine, I exited the tomb and started jogging to the college, I wasn't in combat or anything, it was just me happily skipping around in the snow... and then, CTD. Guess that's my cue to stop playing and go to bed, I have work tomorrow, haha.
> 
> [Crashlog](https://pastebin.com/LKjCwLt5)

**Comment by sirlach** [comment]
I'm getting CTD's in 5.9.0 every 20-30 mins of game time. 

[crash-2024-06-19-12-14-53.log](https://github.com/user-attachments/files/15900732/crash-2024-06-19-12-14-53.log)

**Comment by SteveTownsend** [comment]
This is the instruction that shows up in the first crash

    [ 0] 0x7FFF725AC6C0 SmartHarvestSE.dll+008C6C0    movzx ebx, byte ptr [rbx+0x1A] |  I:\GitHub\SmartHarvestSE\src\Looting\ReferenceFilter.cpp:285 ?RecordReference@ReferenceFilter@shse@@AEAAXPEAVTESObjectREFR@RE@@@Z

similar to crash log from sirlach

	[RSP+0  ] 0x20F1D8CC6E9      (void* -> SmartHarvestSE.dll+008C6E9	test rax, rax |  I:\GitHub\SmartHarvestSE\src\Looting\ReferenceFilter.cpp:298 ?RecordReference@ReferenceFilter@shse@@AEAAXPEAVTESObjectREFR@RE@@@Z)

second crash log has this 

	[RSP+38 ] 0x7FFE08DDCB0C     (void* -> SmartHarvestSE.dll+008CB0C	mov rbx, [rbx] |  I:\GitHub\SmartHarvestSE\src\Looting\ReferenceFilter.cpp:402 ?RecordCellReferences@ReferenceFilter@shse@@AEAAXPEAVTESObjectCELL@RE@@_N@Z)
