### ISSUE TITLE
recurrence of CTD

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/SmartHarvestSE#503]
persistent REFRs again, user [himom4](https://www.nexusmods.com/skyrimspecialedition/users/53702081)

> sorry, but I crashed randomly again.
> [crashlog](https://pastebin.com/65RBCk0d)

Last attempt will be to refresh the persistent REFR list on game reload

**Comment by SteveTownsend** [comment]
Added some logs in private build. Another report from same user:

> another one, but this time I had not loaded/reloaded in a while, but I was checking a few things in the console, closed it, switched outfit thru Skyrim Outfit mod, started moving & I crashed a couple of secs after.
> [crashlog](https://pastebin.com/V8PQ85bi)

**Comment by MokahTGS** [comment]
Seeing this as well.  CTD randomly.

Crash Log: https://pastebin.com/iMw7mQ8K

**Comment by SteveTownsend** [comment]
Similar - null REFR pointer, Nexus user [himom4](https://www.nexusmods.com/users/53702081)

> Well, that took a while (guess it's a good thing)
> [crashlog](https://pastebin.com/zL3NbWAu)
> ﻿[Havestlog](https://drive.google.com/file/d/10OxOm030-qEkiFzwDvFSb54PvQUpxl5A/view?usp=sharing)

**Comment by SteveTownsend** [comment]
A new report via Nexus bugs from [GeoPiroi](https://www.nexusmods.com/skyrimspecialedition/users/1546170)
Esp. when fast traveling

> I constantly have a crash, here is the problem:
> 
> SkyrimSE v1.6.1170
> trainwreck v1.4.0
> Unhandled exception "EXCEPTION_ACCESS_VIOLATION" at 0x7FFA770BC6C4 SmartHarvestSE.dll+008C6C4 shse::ReferenceFilter::RecordReference
> SYSTEM SPECS:
>     OS: Microsoft Windows 11 Pro 24H2 26120.961
>     CPU: AuthenticAMD AMD Ryzen 5 5600H with Radeon Graphics         
>     GPU #1: NVIDIA GeForce RTX 3070 Laptop GPU
>     GPU #2: AMD Radeon(TM) Graphics
>     GPU #3: Microsoft Basic Render Driver
>     RAM: 13.00 GiB/15.36 GiB
>     PAGE FILE: 23.96 GiB/34.36 GiB
> PROBABLE CALL STACK:
>     [0 ] 0x7FFA770BC6C4 SmartHarvestSE.dll+008C6C4 shse::ReferenceFilter::RecordReference
>         [I:\GitHub\SmartHarvestSE\src\Looting\ReferenceFilter.cpp:288]
>         call qword ptr [rax+380h]
>     [1 ] 0x7FFA770BCB1C SmartHarvestSE.dll+008CB1C shse::ReferenceFilter::RecordCellReferences
>         [I:\GitHub\SmartHarvestSE\src\Looting\ReferenceFilter.cpp:406]
>         mov rax,[rbx]
>     [2 ] 0x7FFA770BCC7B SmartHarvestSE.dll+008CC7B shse::ReferenceFilter::FilterNearbyReferences
>         [I:\GitHub\SmartHarvestSE\src\Looting\ReferenceFilter.cpp:439]
>         add rbx,8
>     [3 ] 0x7FFA770BFFBA SmartHarvestSE.dll+008FFBA shse::ScanGovernor::LootAllEligible
>         [I:\GitHub\SmartHarvestSE\src\Looting\ScanGovernor.cpp:575]
>         nop
>     [4 ] 0x7FFA770C047A SmartHarvestSE.dll+009047A shse::ScanGovernor::DoPeriodicSearch
>         [I:\GitHub\SmartHarvestSE\src\Looting\ScanGovernor.cpp:656]
>         call 0000000000004D46h
>     [5 ] 0x7FFA77110A7E SmartHarvestSE.dll+00E0A7E shse::PluginFacade::ScanThread
>         [I:\GitHub\SmartHarvestSE\src\PluginFacade.cpp:249]
>         jmp 0FFFFFFFFFFFFFD12h
>     [6 ] 0x7FFA77110179 SmartHarvestSE.dll+00E0179 `shse::PluginFacade::Start'::`2'::<lambda_1>::operator()
>         [I:\GitHub\SmartHarvestSE\src\PluginFacade.cpp:126]
>         int3
>     [7 ] 0x7FFA771113F9 SmartHarvestSE.dll+00E13F9 std::invoke<`shse::PluginFacade::Start'::`2'::<lambda_1> >
>         [C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include\type_traits:1729]
>         int3
>     [8 ] 0x7FFA771113D6 SmartHarvestSE.dll+00E13D6 std::thread::_Invoke<std::tuple<`shse::PluginFacade::Start'::`2'::<lambda_1> >,0>
>         [C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include\thread:60]
>         int3
>     [9 ] 0x7FFB4A784EA0       ucrtbase.dll+0014EA0
>         mov ecx,eax
>     [10] 0x7FFB4B721ED7       KERNEL32.DLL+0031ED7 BaseThreadInitThunk
>         mov ecx,eax
>     [11] 0x7FFB4CAFA95C          ntdll.dll+00DA95C RtlUserThreadStart
>         jmp short 000000000000002Ah
>

**Comment by SteveTownsend** [comment]
More Nexus logs from [genera90](https://www.nexusmods.com/users/37161085)

Obviously I am missing something about the life cycle of persistent REFRs. Need to add diagnostics and try some other things.

> Ever since I updated to version 5.9.2 from version 5.8.0, I've been getting CTD quite frequently in the wild. (Never occur inside cities / buildings / dungeons.)
> I also noticed it gets worse after I'm longer into the save, but my save is only around 7MB so there's no bloat.
> It doesn't improve even after I:
> 1) Turned off excess inventory function
> 2) Pause autoloot function
> 
> These are some of the crash logs:
> 1) This one before turning off excess inventory: https://pastebin.com/BeHVrXBx
> 2) This one after I turned off excess inventory transfer: https://pastebin.com/C8KVygSQ
> 3) This one after I paused autoloot: https://pastebin.com/ukr1WCHG

**Comment by SteveTownsend** [comment]
disabled the offending code for now
