### ISSUE TITLE
Situational looting issue

### ISSUE THREAD

**Issue by Firesparq** [SteveTownsend/SmartHarvestSE#55]
What:
Even while having set the looter to avoid crime conditions (allow looting of friendly NPCs), occasionally the loot script will loot something and it will be registered as a crime against your character.

Conditions:
- Currently on v1.1
- Have 'Law-abiding while not sneaking' (under 'Looting rules and Defaults') set to prevent crimes.

Work-around:
- Updated 'Law-abiding when not sneaking' to 'ownerless only' and have Law-abiding when sneaking' set to prevent crimes.
This isn't a true work-around, as if you're detected, you still have a chance of being registered as commiting a crime.

This work-around has pointed out something however, your looting script is detecting NPC (shop) chests. This means I cannot crouch in shop locations, else NPC's have their entire stock looted.
I'm happy to make another bug ticket if you'd like, and link it to this one if that would be easier to track.

EDIT: I'm updating this as circumstances have changed. I'm still running using my workaround settings, but I automatically looted something that caused a bounty while not sneaking (set to ownerless)

**Comment by SteveTownsend** [comment]
Thanks for the details. 

I have a fix under test that blocks vendor chests from looting. They're not marked as Owned, so I had to come up with other rules to make this work. It would be best if I gave you this drop so we don't revisit that problem, and to see how much your experience issue is improved by this extra restriction. I can drop this on Google Drive later today if you'd have time to try it out.

Can you provide specific examples with triggering item/location/repro steps, including sneaking/detected vs not sneaking, and your crime check settings for each apparently-separate issue? It's fine to track it all here for now.

**Comment by Firesparq** [comment]
Yes, I'd be happy to check that for you.

Are you looking for exact examples of when these instances occur? Or my current settings that is resulting in the crime looting?

**Comment by SteveTownsend** [comment]
Both, would be great. I tried this a bit with latest code and could not
force theft, maybe the vendor chest change is fixing it. Thanks!

**Comment by Firesparq** [comment]
It could also be another mods interaction :thinking: 

I am running epic restoration, which allows for improved NPC disposition. I'm wondering if that could be playing havoc?

The two instances that have occurred during today's session was in Ivarstead (both in the open world, and in the Vilemyr Inn), and Winterhold (in the open town). In all instances it seems to be something very small (<50 gold in value). It may be that whitelisted items are ignoring ownership rules perhaps? :thinking: 

In any case, my settings haven't changed from what I listed above. While not sneaking, I have it set to look ownerless, and while sneaking set to avoid crime. In today's session, all instances of detected crime occurred while walking around (not sneaking)

**Comment by SteveTownsend** [comment]
I didn't have the right settings. I'll try this again tomorrow or later as
you described.

**Comment by SteveTownsend** [comment]
I tried again to repro this without success. One thing you mentioned though pointed me to a bug: whitelist items bypass the crime-check, that's not correct. I'll fix this in 1.3.0.0 which is imminent. I'll test this myself before finalizing the code.

**Comment by SteveTownsend** [comment]
Here is the repro:
```
J:\GitHub\SmartHarvestSE\debugs.cpp(135): [VERBOSE] {30628} (2020-06-18 02:59:08 PM) 0x000319e3 0x20(32) [Tankard] - typename whitelist
J:\GitHub\SmartHarvestSE\tasks.cpp(61): [VERBOSE] {30628} (2020-06-18 02:59:08 PM) Crime to loot REFR, cannot loot
J:\GitHub\SmartHarvestSE\tasks.cpp(74): [MESSAGE] {30628} (2020-06-18 02:59:08 PM) Block owned/illegal-to-loot REFR: Tankard/0x000319e3
J:\GitHub\SmartHarvestSE\tasks.cpp(328): [VERBOSE] {30628} (2020-06-18 02:59:08 PM) pick up REFR to whitelisted 0x000319e3
J:\GitHub\SmartHarvestSE\tasks.cpp(370): [VERBOSE] {30628} (2020-06-18 02:59:08 PM) Enqueue SmartHarvest event
```

**Comment by SteveTownsend** [comment]
Here is the test evidence of working fix to skip 'illegal' whitelist items - no _SmartHarvest enqueue:
```
J:\GitHub\SmartHarvestSE\tasks.cpp(921): [VERBOSE] {944} (2020-06-18 03:25:27 PM) Process REFR 0x000e4f0d with base object Blue Dartwing/0x000e4f0c
J:\GitHub\SmartHarvestSE\debugs.cpp(135): [VERBOSE] {944} (2020-06-18 03:25:27 PM) 0x000e4f0c 0x1e(30) [Blue Dartwing] - typename whitelist
J:\GitHub\SmartHarvestSE\tasks.cpp(61): [VERBOSE] {944} (2020-06-18 03:25:27 PM) Crime to loot REFR, cannot loot
J:\GitHub\SmartHarvestSE\tasks.cpp(74): [MESSAGE] {944} (2020-06-18 03:25:27 PM) Block owned/illegal-to-loot REFR: Blue Dartwing/0x000e4f0c
```
