### ISSUE TITLE
Add mining tools prerequisites for ore veins as an option.

### ISSUE THREAD

**Issue by Lywzc** [SteveTownsend/SmartHarvestSE#64]
Make ore veins only lootable if you have a pickaxe, Rocksplinter, Notched Pickaxe or Ancient Nordic Pickaxe. Not sure if Stalhrim is minable without Ancient Nordic Pickaxe now but it should be the same as the ordinary veins. If there are other things that require special items or magic or perk to be collected/mined add those too.

This should be an option that one can turn on or off. I am not sure what the default should be but I prefer on.

**Comment by SteveTownsend** [comment]
Ore Veins seem reasonable. I can't commit to synthesizing every possible perk and condition that prevents manual looting in the game. Please raise others as individual issues

**Comment by Lywzc** [comment]
I don't remember other instances too aside from ore veins and stalhrim. That's why I use others because I think there are no other examples but I am not sure. For now these two will be sufficient.

**Comment by SteveTownsend** [comment]
great, sounds good.

**Comment by Lywzc** [comment]
All activators attached with MineOreScript are subjects, including Heart Stone Deposits, Geodes and Shellbugs.

**Comment by SteveTownsend** [comment]
Yes I already pulled logic from various mining  scripts to support auto
mine. The tool check is also visible and I can recreate given time
