### ISSUE TITLE
validate auto mining with CCOR only, no CACO

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/SmartHarvestSE#86]
Nexus comment:

> Is anyone else having issues with CCOR + Smart Harvest when they try to harvest ore?
> CCOR does change the mining scripts but I don't remember this issue back in AutoHarvest.

**Comment by timorei** [comment]
Hey, this is the chillshock from the nexus-threads. I just dropped in to report that I have CCOR only and ore does not get picked up by SH, but I can still mine in manually and it gives the loot it's supposed to according to CCOR (gems and such).

**Comment by jtolmer** [comment]
FYI, I play with CCOR, but not CACO, and I have not noticed a problem. Ore veins auto mine as I walk over them.

**Comment by timorei** [comment]
Interesing. So it's either the CCOR settings, other mods or loadorder.
I got a weightless ores mod, that should not affect the mines, though.
loadorder
171: CCOR 
14: SH

**Comment by SteveTownsend** [comment]
I would not assume anything. If you can send me to LO we can make sure.
Mods do some crazy stuff!

**Comment by timorei** [comment]
Ok, so here's the loadorder:
[loadorder.txt](https://github.com/SteveTownsend/SmartHarvestSE/files/4843694/loadorder.txt)

Which log specifically would help you?

**Comment by SteveTownsend** [comment]
Don't worry, this is fine.

InstantMining.esp looks very likely to conflict with SHSE. I'll dig more
and confirm tomorrow.

**Comment by timorei** [comment]
Ok, so here's something: I purged all mods and all configs. Reinstalled it all. Cursed a lot due to loadorder reconstruction (conflicts). And then configured the whole thing anew. And you could quess it: It now works ootb. 
At least in my case it seems to be either bad mod leftovers or bad config. :/

**Comment by SteveTownsend** [comment]
Well however it happened, I'm glad it's working for you now.

**Comment by SteveTownsend** [comment]
CCOR works OK, documented on mod page
