### ISSUE TITLE
Add support for World's Dawn and player-made enchantments

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/SmartHarvestSE#90]
Nexus feature request, for 1.6++ if feasible

> It would be nice if you could add support to recognize script enchanted equipments. I played with World's Dawn but both your mod and AutoHarvest couldn't loot equipment enchanted by it.
The SSE version: https://drive.google.com/file/d/1GXpW-GYD-Lp0LOurw4Zigr8g6ubXBPT6

**Comment by SteveTownsend** [comment]
I have some questions on how World's Dawn works. I guess you want weapons that have the mod's player-created enchantments applied looted from dead NPCs based on the enchanted-weapon category, and with their enchantments intact? Is that how manual looting of such NPCs works - NPC armor/weapons that the mod augments keep their magic effects after NPC death?

**Comment by GarrixWong** [comment]
The enchantments is applied before the npc'death. It use a cloak magic to scan npc around player. It use form list to store magic effects and create user-enchantment based on these magic effects. I will look into the World's Dawn's script and tell you which one do such things.

**Comment by GarrixWong** [comment]
When I use Auto Harvest, I noticed that If I do save and load around dead body with equipments enchanted by World's Dawn, It can be looted automatically. So I guess the Auto Harvest use cache to store scanned objects. The item hasn't been enchanted yet at the time the cache was generated. When the game reloaded, the cache was emptied so the mod can recognize the enchanted equipments.

**Comment by SteveTownsend** [comment]
Yeah, when I looked at the world's dawn scripts I wondered if SHSE would
work with this more easily than AH. I think from what you said it should be
possible, even if it does not work right away. Let me know what you find
and I'll look some more tomorrow. I think the script function you want is
CheckEquipment

**Comment by SteveTownsend** [comment]
FYI SHSE delays looting dead bodies for a few seconds so that leveled items
added on death get finalized. My thought is that this logic or a variation
of it could make World's Dawn SHSE-compatible with zero or a little work.

**Comment by GarrixWong** [comment]
I edited the first comment but I’m afraid that you can't see it from mail, so I put it here:
EDIT: It didn't use cloak magic to achieve that. xtd_periodicscript.psc use ScanCellNPCs to scan npcs and containers around player.
xtd_configex.psc is responsible for processing the npcs and xtd_lonewolffollowerscheck.psc is for containers.
ApplyPlayerMadeEnchantment in xtd_basescript.psc is used by xtd_configex.psc and xtd_lonewolffollowerscheck.psc to apply enchantment to equipment.
CheckEquipment is only used for test purpose. 

MiscUtil.ScanCellNPCs is provided by PapyrusUtil SE - Scripting Utility Functions.

By the way, World's Dawn is designed to allow npc  to use its enchantment, so their equipments are already enchanted when they are alive.

**Comment by SteveTownsend** [comment]
SHSE only processes NPCs after they are dead. If the WD enchantments on items were to show up at that point in their inventory, I cannot think why we would not just loot those items like any other enchanted object. 

I see that the WD scripts use SKSE _WornObject_ to process the target's equipped weapon/armor on the fly, maybe that is the difference? If the items are manually lootable after NPC death, they must show up in inventory but maybe not tagged in the 'normal' way as enchanted.

**Comment by GarrixWong** [comment]
It use WornObject to create player-made enchantment, and you can only use WornObject.GetEnchantment or ObjectReference.GetEnchantment to get player-made enchantment.
Weapon.GetEnchantment and Armor.GetEnchantment is used to get enchantment binded to equipment.

BTW, You may need use CommonLibSSE's TESForm::GetGoldValue to get the gold value of equipments with player-made enchantment.

**Comment by SteveTownsend** [comment]
OK so that's the critical point that's missing here. CLSSE at present does
not have WornObject but I should be able to make code to handle it by
reference to SKSE. RSM might be interested in picking up the results for
CLSSE, we'll see.

I'll take a look at the Gold Value API - I currently have calculations that
I pulled over from AHSE but they don't always give the right result afai
can see.

**Comment by SteveTownsend** [comment]
This is not going to fit into v1.6 but should be doable in next few days for v1.7

**Comment by GarrixWong** [comment]
Thank you! I'm looking forward to your new version. I haven't tested the GetGoldValue but I believe it can get the correct value after reviewing its implemention.

**Comment by SteveTownsend** [comment]
I'll do what I can to test locally but if you have a working WD/SHSE setup I will ask for your help with this - is that OK?

**Comment by GarrixWong** [comment]
No problem, I will test it in a few days.

**Comment by SteveTownsend** [comment]
awesome, thanks

**Comment by GarrixWong** [comment]
I add support for player-created enchantment, it work well for me now, and the gold value is also correct.
Code is here: https://github.com/GarrixWong/SmartHarvestSE/tree/develop

**Comment by SteveTownsend** [comment]
I can review the code and add this to the core mod for upcoming release 1.6
or 1.7, if you like. Thanks for doing the work!

**Comment by SteveTownsend** [comment]
This looks pretty much ready to go, I can integrate into v1.6 today if you
are OK with that. I"m happy it was not necessary to add full-blown
WornObject support.

**Comment by GarrixWong** [comment]
I'm glad that it can help. You can integrate it into v1.6, I want to play with this feature as soon as possible.

**Comment by SteveTownsend** [comment]
OK I'll have a test build going out to you and one other tonight, I'll drop
that on GDrive when it's ready and let you know

**Comment by SteveTownsend** [comment]
playtest build is at
https://drive.google.com/file/d/1tbm3eH5B8HIUilUPd7mAAlT_Ox2fgzb5/view?usp=sharing,
let me know if this works. Code is all pushed to the main Github repo

**Comment by GarrixWong** [comment]
I have tested this build, it worked well with World's Dawn.

**Comment by SteveTownsend** [comment]
That's great, thanks for writinging the code and testing!

Can I credit you for the work using Nexus id or GitHub name, when releasing
it?

**Comment by GarrixWong** [comment]
Sure, thank you! I prefer using my Nexus id.

**Comment by SteveTownsend** [comment]
Will do. Waiting for feedback on Hunterborn testing and then I'll push it
out.

**Comment by SteveTownsend** [comment]
verified for release in v1.6
